# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=media.models.make_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=media.models.make_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('place', models.CharField(choices=[('PH', 'Perfume House'), ('SC', 'Story of the Creek')], max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
