# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(choices=[('PH', 'Perfume House'), ('SC', 'Story of the Creek')], default='PH', max_length=100),
        ),
    ]
