# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=products.models.make_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
        ),
    ]
